[tools]
node = 'lts'
bun = "latest"
ruby = "latest"
usage = "latest"
deno = "latest"
"npm:pnpm" = "latest"

[settings]
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates
experimental = true
